apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-
spec:
  entrypoint: hello
  templates:
  - name: hello
    inputs:
      parameters:
      - name: s
    script:
      image: hera-scratch:v1
      source: '{{inputs.parameters}}'
      args:
      - -m
      - hera.workflows.runner
      - -e
      - hera_scratch.workflow:hello
      command:
      - python
  arguments:
    parameters:
    - name: s
      value: world
